#!/bin/bash

set -e
TMPDIR="${TMPDIR:-/tmp}"

if [ -z "$BAZEL_BIN_LOC" ]; then
  if [ -n "$ROCKET_BRANCH" ]; then
    BAZEL_BIN_LOC=~/.bazel_binaries_${EXECUTOR_NUMBER}
  else
    BAZEL_BIN_LOC=~/.bazel_binaries
  fi
fi

mkdir -p "$BAZEL_BIN_LOC"

if [ "$(uname -s)" == "Linux" ]; then
  export BAZEL_LAUNCHER_PLATFORM_NAME='linux'
elif [ "$(uname -s)" == "Darwin" ]; then
  export BAZEL_LAUNCHER_PLATFORM_NAME='darwin'
else
  "Your platform $(uname -s) is unsupported, sorry"
  exit 1
fi

BAZELISK_VERSION=v1.16.0

EXPECTED_BINARY_LOCATION="$BAZEL_BIN_LOC/$BAZELISK_VERSION"
if [ ! -f "$EXPECTED_BINARY_LOCATION" ]; then
  ARCH="$(uname -m)"
  suffix="amd64"
  if [ "$ARCH" == "arm64" ]; then
    suffix="arm64"
  fi
  DOWNLOAD_URL="https://github.com/bazelbuild/bazelisk/releases/download/${BAZELISK_VERSION}/bazelisk-${BAZEL_LAUNCHER_PLATFORM_NAME}-${suffix}"
  TARGET_PATH="${EXPECTED_BINARY_LOCATION}_tmp_${RANDOM}"
  curl -f -L -o "$TARGET_PATH" "$DOWNLOAD_URL"
  if [ ! -f $EXPECTED_BINARY_LOCATION ]; then
    mv $TARGET_PATH $EXPECTED_BINARY_LOCATION
    chmod +x $EXPECTED_BINARY_LOCATION
  fi
fi

exec "$EXPECTED_BINARY_LOCATION" "$@"

