ROLLUP_DEPENDENCIES = [
    "//:node_modules/rollup-plugin-typescript2",
    "//:node_modules/rollup-plugin-postcss",
    "//:node_modules/@rollup/plugin-json",
    "//:node_modules/@rollup/plugin-node-resolve",
    "//:node_modules/@rollup/plugin-commonjs",
    "//:node_modules/sass",
    "//:node_modules/rollup-plugin-copy",
    "//:node_modules/rollup-plugin-node-externals",
    "//:node_modules/builtin-modules",
    "//:node_modules/@rollup/plugin-babel",
    "//:node_modules/@babel/plugin-transform-typescript",
    "//:node_modules/@babel/plugin-proposal-class-properties",
    "//:node_modules/@babel/preset-typescript",
    "//:node_modules/@babel/preset-env",
    "//:node_modules/@babel/preset-react",
    "//:babel_config",
]

SRC_DEPENDENCIES = [
    "//:node_modules/@types/long",
    "//:node_modules/@types/node",
    "//:node_modules/@types/react",
    "//:node_modules/@types/react-dom",
    "//:node_modules/cheerio",
    "//:node_modules/classnames",
    "//:node_modules/fs-extra",
    "//:node_modules/glob",
    "//:node_modules/html-react-parser",
    "//:node_modules/html-to-text",
    "//:node_modules/juice",
    "//:node_modules/lodash",
    "//:node_modules/moment",
    "//:node_modules/pino",
    "//:node_modules/protobufjs",
    "//:node_modules/react",
    "//:node_modules/react-dom",
]
